### ISSUE TITLE
When quitting, tes3mp crashes instead of closing peacefully

### ISSUE THREAD

**Issue by davidcernat** [TES3MP/TES3MP#71]
We should make it close the way regular OpenMW does.

**Comment by Koncord** [comment]
Can you confirm this on Windows?

**Comment by davidcernat** [comment]
I only use Windows and it crashes all the time.

**Comment by Koncord** [comment]
Maybe fixed by fa0a55c2a9d50f08dabfd81d5e60a6ab3ba3e2a7

**Comment by davidcernat** [comment]
That fixes the client on Windows. Nice.

However, the server still crashes.

**Comment by Koncord** [comment]
@davidcernat, can you provide server's backtrace?

**Comment by davidcernat** [comment]
It's unclear how one would provide that in the unusual development environment we have for the server on Windows.

**Comment by davidcernat** [comment]
Starting with f865246955ebc932b2e318d34122fbaa897e90f7, it is possible to build the server with Breakpad enabled.

The point of doing so was so that the server crashing could generate a dump file to clarify the reason for the crashes.

Rather amusingly, with Breakpad enabled, closing the server always shuts it down peacefully without an error message from Windows, and generates no dump file when doing so.

That being said, I guess it does technically resolve this issue...
